version: "3.5"

services:

  # Auth-image #####################
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin123
    ports:
      - 8080:8080
    networks:
      - custom_network
  ##################################

  # APIS-images ###################################

  ## Golang API ##
  go-api:
    build: ./apis/go-gyn
    container_name: go-api
    restart: always
    ports:
      - "8090:8080"
    networks:
      - custom_network

  ### JAVA API ###
  spring-api:
    build: ./apis/java-spring
    container_name: spring-api
    restart: always
    ports:
      - "8085:8080"
    networks:
      - custom_network
  ##################################

  # Proxy from Ory #################
  oath-keeper:
    build: ./oath-image
    command: -c /config.yaml serve
    container_name: oath
    restart: always
    ports:
      - "4455:4455"
      - "4456:4456"
    networks:
      - custom_network
  ##################################

  # Client side As front end #################
  client:
    build: ./client
    container_name: client
    restart: always
    ports:
      - "8081:80"
    networks:
      - custom_network
  ##################################

networks:
  custom_network:
    external:
      name: poc


